### ISSUE TITLE
hi is this still under development?

### ISSUE THREAD

**Issue by tws0002** [eoyilmaz/stalker_pyramid#1]
hi,

I have successfully run `stalker_pyramid2` server. 
here is the page I get 
![stalker_pyramid](https://user-images.githubusercontent.com/7018625/48047884-80802c00-e1d4-11e8-90a7-da7d21b62d17.PNG)
how can I get the project view from anima?

Thanks 
Desmond

**Comment by eoyilmaz** [comment]
I'll try to release Stalker Pyramid (this project) in the following months.

**Comment by eoyilmaz** [comment]
Stalker Pyramid2 will be build on top of Angular2/4, and it needs a UI designer to design the UI.

**Comment by eoyilmaz** [comment]
Basically Stalker Pyramid2 will be more responsive.

**Comment by tws0002** [comment]
meaning `Stalker Pyramid` will use Angular2/4 as well right?
so the coming release of `Stalker Pyramid` will be integrated with anima pipeline?
are you using this for production now?

**Comment by tws0002** [comment]
great. can't wait to test the `Stalker Pyramid` that you going to release soon. because I using `anima` pipeline workflow in our production too. 

can I say `Stalker Pyramid` is kind of like shotgun?

**Comment by eoyilmaz** [comment]
> can I say Stalker Pyramid is kind of like shotgun?

Exactly

**Comment by eoyilmaz** [comment]
After 2 years and 2 months I've released the code, FYI. Now closing this issue.
