### ISSUE TITLE
hey eoyilmaz 

### ISSUE THREAD

**Issue by tws0002** [eoyilmaz/stalker_pyramid#1]
hey eoyilmaz,

is this stalker_pyramid will work with anima and stalker as a web base task manager?
how can I try this out?

Desmond

**Comment by eoyilmaz** [comment]
Yes and no.

This is the stripped down development version of Stalker Pyramid that doesn't have any closed source dependencies.

So in its current form it is not working (at least not the frontend, backend is okay-ish).

I created this project so we can develop it together.

**Comment by tws0002** [comment]
Got it thanks for the info.

**Comment by tws0002** [comment]
may I ask what will be the difference between `Stalker Pyramid` and` Stalker Pyramid2` repository?

**Comment by eoyilmaz** [comment]
Stalker Pyramid will stay like that, I'm just trying to make it work with the npm style packages and migrating some of the code to TypeScript. But it will not use Angular. Stalker Pyramid2 will use Angular2/4.

And yes we are using Stalker Pyramid in production. We develeoped it for a feature animated movie and used it in tons of other commercial and and a couple of tv series projects.
